---

- hosts: boklm-tbb-nightly-build
  roles:
      - role: tbb-builder
      - role: tbb-nightly-build
      - role: unattended-upgrades
      - role: mta
  vars_files:
      - vaulted_vars/boklm-tbb-nightly/dma-auth.yml
