---
martools_version: 9.0.2
martools_url: https://archive.torproject.org/tor-package-archive/torbrowser/
martools_gpg_keyring: keyring/torbrowser.gpg
builds_url: /srv/tbb-nightlies-master.torproject.org/htdocs/nightly-builds/tor-browser-builds
torbrowser:
  publish_dirs:
    - nightly-linux-x86_64
    - nightly-linux-i686
    - nightly-windows-x86_64
    - nightly-windows-i686
    - nightly-macos
  nss_db_dir: nssdb
  appname_marfile: tor-browser
  appname_bundle: tor-browser
basebrowser:
  publish_dirs:
    - basebrowser-nightly-linux-x86_64
    - basebrowser-nightly-linux-i686
    - basebrowser-nightly-windows-x86_64
    - basebrowser-nightly-windows-i686
    - basebrowser-nightly-macos
  nss_db_dir: nssdb-basebrowser-1
  appname_marfile: base-browser
  appname_bundle: base-browser
nss_certname: nightly-marsigner
gpg_keyring: keyring/torbrowser-nightly.gpg
rsync_dest: /srv/tbb-nightlies-master.torproject.org/htdocs/nightly-updates/
post_rsync_cmd: 'unset LD_PRELOAD && /usr/local/bin/static-update-component nightlies.tbb.torproject.org'
tmp_dir: /home/tbb-nightlies/tmp
