---
download:
    mars_url: https://nightlies.tbb.torproject.org/nightly-updates
build_targets:
    linux-i686: Linux_x86-gcc3
    linux-x86_64: Linux_x86_64-gcc3
    windows-i686:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    windows-x86_64: WINNT_x86_64-gcc3-x64
    macos:
      - Darwin_x86_64-gcc3
      - Darwin_aarch64-gcc3
channels:
    nightly: nightly_version
versions:
    nightly_version:
        platformVersion: 115.1.0
        detailsURL: http://umj4zbqdfcyevlkgqgpq6foxk3z75zzxsbgt5jqmfxofrbrjh3crbnad.onion/
        migrate_langs:
            pt-PT: pt-BR
        macos:
            minSupportedOSVersion: 16.0.0
        windows-i686:
            minSupportedOSVersion: 6.1
            minSupportedInstructionSet: SSE2
        windows-x86_64:
            minSupportedOSVersion: 6.1
            minSupportedInstructionSet: SSE2
        linux-i686:
            minSupportedInstructionSet: SSE2
        linux-x86_64:
            minSupportedInstructionSet: SSE2
mar_compression: xz
