---
download:
    mars_url: https://nightlies.tbb.torproject.org/nightly-updates
appname_marfile: tor-browser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    win64: WINNT_x86_64-gcc3-x64
    macos:
      - Darwin_x86_64-gcc3
      - Darwin_aarch64-gcc3
channels:
    nightly: nightly_version
versions:
    nightly_version:
        platformVersion: 68.2.0
        detailsURL: http://umj4zbqdfcyevlkgqgpq6foxk3z75zzxsbgt5jqmfxofrbrjh3crbnad.onion/
        migrate_langs:
            pt-PT: pt-BR
        minSupportedInstructionSet: SSE2
        macos:
            minSupportedOSVersion: 16.0.0
        win32:
            minSupportedOSVersion: 6.1
        win64:
            minSupportedOSVersion: 6.1
mar_compression: xz
