---
tmp_dir: '[% c("tmp_dir") %]'
create_downloads_json: 1
appname_marfile: tor-browser
appname_bundle_android: tor-browser
appname_bundle_macos: TorBrowser
appname_bundle_linux: tor-browser
appname_bundle_win32: torbrowser-install
appname_bundle_win64: torbrowser-install-win64
releases_dir: [% path(c('output_dir')) %][% IF ! c("var/nightly") %]/signed[% END %]
download:
    archive_url: https://archive.torproject.org/tor-package-archive/torbrowser
    gpg_keyring: ../../keyring/torbrowser.gpg
    bundles_url: https://dist.torproject.org/torbrowser
    mars_url: https://cdn.torproject.org/aus1/torbrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    win64: WINNT_x86_64-gcc3-x64
    macos:
      - Darwin_x86_64-gcc3
      - Darwin_aarch64-gcc3
channels:
    [% c('var/channel') %]: [% c("var/torbrowser_version") %]
versions:
    [% c("var/torbrowser_version") %]:
[% IF c("var/create_unsigned_incrementals") -%]
        releases_dir: [% path(c('output_dir')) %]/unsigned
[% END -%]
        platformVersion: [% pc('firefox', 'var/firefox_platform_version') %]
        detailsURL: https://blog.torproject.org/new-release-tor-browser-[% c("var/torbrowser_version") FILTER remove('\.') %]
        incremental_from:
[% SET incr_from = c("var/nightly") ? c("var_p/nightly_torbrowser_incremental_from") : c("var/torbrowser_incremental_from");
   FOREACH v IN incr_from -%]
          - [% v %]
[% END -%]
        # for example, osx32: osx64
        migrate_archs:
        # for example, pt-PT: pt-BR
        migrate_langs:
        minSupportedInstructionSet: SSE2
        # minSupportedOsVersion on macOS corresponds to the Darwin version ( https://en.wikipedia.org/wiki/Darwin_(operating_system) )
        macos:
            # macOS v10.12.0
            minSupportedOSVersion: 16.0.0
        # minSupportedOsVersion on Windows corresponds to the operating system version ( https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version )
        win32:
            # Windows 7
            minSupportedOSVersion: 6.1
        win64:
            # Windows 7
            minSupportedOSVersion: 6.1
mar_compression: xz
tag: 'tbb-[% c("var/torbrowser_version") %]-[% c("var/torbrowser_build") %]'
htaccess_rewrite_rules:
    alpha: |
        # bug 26569: Redirect pre-8.0a9 alpha users to a separate update directory
        RewriteRule ^[^/]+/8\.0a[12345678]/.* https://aus1.torproject.org/torbrowser/update_pre8.0a9/alpha/$0 [last]
        RewriteRule ^[^/]+/[4567]\..*/.* https://aus1.torproject.org/torbrowser/update_pre8.0a9/alpha/$0 [last]
    release: |
        # bug 26570: Redirect pre-8.0 stable users to a separate update directory
        RewriteRule ^[^/]+/[4567]\..*/.* https://aus1.torproject.org/torbrowser/update_pre8.0/release/$0 [last]
